package:
  name: "pylebedev"
  version: "1.1.0"

source:
  path: .

build:
  include_recipe: False
  noarch: python

requirements:
  build:
    - numpy>=1.21
    - python>=3.9

  host:
    - pip
    - python>=3.9
    - setuptools
    - numpy>=1.21

  run:
    - python>=3.9
    - numpy>=1.21

test:
  requires:
    - numpy
    - setuptools
    - pytest
  source_files:
    - tests/*.py
  commands:
    - pytest tests/*.py

about:
  home: https://github.com/ifilot/pylebedev
  license: GPL3
  license_family: GPL
  summary: Python package for obtainin Lebedev quadrature integration points and weights
  description: See the package README.md for more information.
