name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-pypi:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Install dependencies
      run: |
        yum -y install eigen3-devel libgomp glm-devel
        yum -y install mlocate
        yum -y install gcc
        ls -alh /opt/python/cp*
        /opt/python/cp39-cp39/bin/python -m pip install numpy tqdm cython pytest
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run: /opt/python/cp39*/bin/python setup.py bdist_wheel
    - name: Test
      run: |
        /opt/python/cp39*/bin/python -m pip install numpy nose
        /opt/python/cp39*/bin/pip install pylebedev --no-index -f ./dist
        /opt/python/cp39*/bin/pytest" --verbose tests
    - name: Archive wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/pylebedev-*.whl

  # pypi-publish:
  #   name: Upload release to PyPI
  #   if: github.ref == 'refs/heads/master'
  #   needs: build-linux
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/pytessel
  #   permissions:
  #     id-token: write
  #   steps:
  #   - name: Retrieve packages
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: wheels
  #       path: wheelhouse
  #   - name: Publish package distributions to PyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       packages-dir: wheelhouse/

  build-anaconda:
    runs-on: ubuntu-latest
    container: conda/miniconda3

    steps:
      - name: Prepare build environment
        run: conda install -y conda-build
      - name: Build
        shell: bash -l {0}
        run: |
          conda build .
      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: anaconda-packages
          path: ./anaconda-upload/pylebedev-*.tar.bz2

  # anaconda-publish:
  #   name: Upload release to Anaconda
  #   if: github.ref == 'refs/heads/master'
  #   needs: build-windows
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: anaconda
  #     url: https://anaconda.org/ifilot/pytessel
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Set-up miniconda
  #       uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         activate-environment: test
  #         environment-file: environment.yml
  #         python-version: 3.8
  #         auto-activate-base: false
  #     - name: Retrieve packages
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: anaconda-packages
  #         path: packages
  #     - name: publish-to-conda
  #       shell: bash -l {0}
  #       env:
  #         INPUT_ANACONDATOKEN: ${{ secrets.ANACONDA_TOKEN }}
  #       run: |
  #         export ANACONDA_API_TOKEN=$INPUT_ANACONDATOKEN
  #         anaconda upload packages/*.tar.bz2

